// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/compare-mobile/StackedCards.tsx": () => import("../components/mockups/compare-mobile/StackedCards.tsx"),
  "./components/mockups/compare-mobile/SwipeableTabs.tsx": () => import("../components/mockups/compare-mobile/SwipeableTabs.tsx")
};
